Extend timeout in test JobsBrokerService
This resolves instability in tests, e.g.:
java.lang.RuntimeException: java.util.concurrent.TimeoutException
at ...JobsBrokerServiceTest.waitForFutureOptionalJob()
at ...JobsBrokerServiceTest.getAlotOfJobs()

Redo commit 8aff973214f44a1f4cf95e5330cb9687be1bfa76

Issue-ID: VID-433

Change-Id: Ib366d7c7ffff7ee75a78ff5be5ccd5c970c783dd
Signed-off-by: Ittay Stern <ittay.stern@att.com>